services:
  postgres:
    image: postgres:15
    container_name: postgres
    depends_on:
      postgres_sync:
        condition: service_healthy
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./Database/sql_dev/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
      - ./Database/sql_dev/seed_db_part1.sql:/docker-entrypoint-initdb.d/seed_db_part1.sql
      - ./Database/sql_dev/seed_db_part2.sql:/docker-entrypoint-initdb.d/seed_db_part2.sql
      - ./Database/sql_dev/seed_db_part3.sql:/docker-entrypoint-initdb.d/seed_db_part3.sql
      - ./Database/sql_dev/seed_db_part4.sql:/docker-entrypoint-initdb.d/seed_db_part4.sql
      - ./Database/sql_dev/sync_logs.sql:/docker-entrypoint-initdb.d/sync_logs.sql

    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  postgres_sync:
    image: postgres:15-bookworm
    container_name: postgres_sync
    environment:
      POSTGRES_USER: sync_user
      POSTGRES_PASSWORD: sync_password
      POSTGRES_DB: sync_db
    ports:
      - 5433:5432
    volumes:
    - postgres_sync_data:/var/lib/postgresql/data
    - ./Database/Dump/sync_db_backup.dump:/docker-entrypoint-initdb.d/sync_db_backup.dump
    - ./Database/Dump/restore_sync_db.sh:/docker-entrypoint-initdb.d/restore_sync_db.sh    
    networks:
      - app-network
    command: ["postgres", "-c", "listen_addresses=*", "-c", "log_statement=all"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sync_user -d sync_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:9200 >/dev/null || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.1
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    depends_on:
      elasticsearch:
        condition: service_healthy
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: pgadmin
    ports:
      - 5050:80
    networks:
      - app-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  resources:
    build:
      context: ./Backend/resources_service
      dockerfile: Dockerfile
    container_name: resources
    ports:
      - "3005:3005"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/postgres
      - PORT=3005
      - SENDGRID_API_KEY=${SENDGRID_API_KEY}
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network
    volumes:
      - ./Backend/resources_service:/app
      - /app/generated/prisma

  projects:
    build:
      context: ./Backend/projects_service
      dockerfile: Dockerfile
    container_name: projects
    ports:
      - "3003:3003"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/postgres
      - SENDGRID_API_KEY=${SENDGRID_API_KEY}
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network
    volumes:
      - ./Backend/projects_service:/app
      - /app/generated/prisma

  client:
    build:
      context: ./Backend/clients_service
      dockerfile: Dockerfile
    container_name: client
    ports:
      - "3002:3002"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/postgres
      - SENDGRID_API_KEY=${SENDGRID_API_KEY}
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network
    volumes:
      - ./Backend/clients_service:/app
      - /app/generated/prisma

  documents:
    build:
      context: ./Backend/documents_service
      dockerfile: Dockerfile
    container_name: documents
    ports:
      - "3004:3004"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/postgres
      - SENDGRID_API_KEY=${SENDGRID_API_KEY}
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network
    volumes:
      - ./Backend/documents_service:/app
      - ./Backend/documents_service/uploads:/app/uploads
      - /app/generated/prisma

  planning:
    build:
      context: ./Backend/planning_service
      dockerfile: Dockerfile
    container_name: planning
    ports:
      - "3007:3007"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/postgres
      - SENDGRID_API_KEY=${SENDGRID_API_KEY}
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network
    volumes:
      - ./Backend/planning_service:/app
      - /app/generated/prisma       

  chatbot:
    build:
      context: ./Backend/chatbot_service
      dockerfile: Dockerfile
    container_name: chatbot
    ports:
      - "5599:5599"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/postgres
      - PORT=5599
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ELASTICSEARCH_NODE=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=elastic
    depends_on:
      postgres:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
    networks:
      - app-network
    volumes:
      - ./Backend/chatbot_service:/app
      - /app/node_modules
      - /app/generated/prisma

  email-modules:
    build:
      context: ./Email_Module/email_service_openai
      dockerfile: Dockerfile
    container_name: email-modules
    ports:
      - "4444:4444"
    environment:
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - IMAP_HOST=${IMAP_HOST}
      - IMAP_PORT=${IMAP_PORT}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_SECURE=${SMTP_SECURE}

    networks:
      - app-network

  api-gateway:
    build:
      context: ./Backend/api_gateway
      dockerfile: Dockerfile
    container_name: api-gateway
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/postgres
      - SENDGRID_API_KEY=${SENDGRID_API_KEY}
    depends_on:
      resources:
        condition: service_started
      projects:
        condition: service_started
      client:
        condition: service_started
      documents:
        condition: service_started
    networks:
      - app-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
  postgres_sync_data:
  elasticsearch_data:
