services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./Database/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
      - ./Database/seed_db_part1.sql:/docker-entrypoint-initdb.d/seed_db_part1.sql
      - ./Database/seed_db_part2.sql:/docker-entrypoint-initdb.d/seed_db_part2.sql
      - ./Database/seed_db_part3.sql:/docker-entrypoint-initdb.d/seed_db_part3.sql

volumes:
  postgres_data:
