services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./Database/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
      - ./Database/seed_db_part1.sql:/docker-entrypoint-initdb.d/seed_db_part1.sql
      - ./Database/seed_db_part2.sql:/docker-entrypoint-initdb.d/seed_db_part2.sql
      - ./Database/seed_db_part3.sql:/docker-entrypoint-initdb.d/seed_db_part3.sql

  api-gateway:
    build:
      context: ./Backend/api_gateway
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/postgres
    depends_on:
      - postgres

  client:
    build:
      context: ./Backend/clients_service
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - api-gateway

  projects:
    build:
      context: ./Backend/projects_service
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/postgres
    depends_on:
      - postgres

volumes:
  postgres_data:
